version: '3'
services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: mealplanner
    ports:
      - "5432:5432"
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    image: mealplanner-backend
    container_name: mealplanner-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/mealplanner
      SPRING_DATASOURCE_USERNAME: 
      SPRING_DATASOURCE_PASSWORD: 
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mealplanner-frontend
    ports: 
      - "3000:3000"
    depends_on:
      - back-end
  
      
 


